server:
  port: 5678

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: sidecar-service

sidecar:
  port: 5000
  health-uri: http://localhost:5000/health